services:
  booking-service:
    restart: on-failure
    image: booking-service:latest
    networks:
      - net
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: booking-service
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none

  query-service:
    restart: on-failure
    image: query-service:latest
    networks:
      - net
    env_file:
      - .env
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: query-service
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none

  command-service:
    restart: on-failure
    image: command-service:latest
    networks:
      - net
    ports:
      - "50051:50051"
    env_file:
      - .env
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: command-service
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none

  cassandra:
    restart: on-failure
    image: cassandra:5.0.5
    networks:
      - net
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra"
      CASSANDRA_CLUSTER_NAME: booking-system
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    volumes:
      - cassandra-data:/var/lib/cassandra

  kafka:
    image: apache/kafka:4.1.0
    networks:
      - net
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_LISTENERS: BROKER://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:9092 # BROKER://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-data:/etc/kafka/secrets
      - kafka-data:/mnt/shared/config

  alloy:
    restart: on-failure
    image: grafana/alloy:v1.9.1
    networks:
      - net
    ports:
      - "12345:12345"
    volumes:
      - ./config-docker-compose.alloy:/etc/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/config.alloy

  prometheus:
    restart: on-failure
    image: prom/prometheus:v3.4.1
    networks:
      - net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms

  otel-collector:
    restart: on-failure
    image: otel/opentelemetry-collector-contrib:0.134.1
    networks:
      - net
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    command:
      - --config=/etc/otel-collector.yaml

  loki:
    restart: on-failure
    image: grafana/loki:3.5.5
    ports:
      - "3100:3100"
    networks:
      - net
    user: root
    volumes:
      - ./loki.yaml:/etc/loki.yaml
      - loki-data:/loki/wal
    command:
      - -config.file=/etc/loki.yaml

  tempo:
    restart: on-failure
    image: grafana/tempo:2.8.2
    ports:
      - "3200:3200"
    networks:
      - net
    user: root
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    command:
      - -config.file=/etc/tempo.yaml

  grafana:
    restart: on-failure
    image: grafana/grafana:12.0.1
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

volumes:
  kafka-data:
  cassandra-data:
  prometheus-data:
  tempo-data:
  loki-data:

networks:
  net: