spring:
  application:
    name: booking-service

kafka:
  clientId: ${BOOKING_SYSTEM_KAFKA_BOOKING_SERVICE_CLIENT_ID}
  bootstrapServers: ${BOOKING_SYSTEM_KAFKA_BOOTSTRAP_SERVERS}

query:
  service:
    baseUrl: ${BOOKING_SYSTEM_QUERY_SERVICE_URL}
