spring:
  application:
    name: booking-service
  threads:
    virtual:
      enabled: true

logging:
  structured:
    format:
      console=ecs

kafka:
  clientId: ${BOOKING_SYSTEM_KAFKA_BOOKING_SERVICE_CLIENT_ID}
  bootstrapServers: ${BOOKING_SYSTEM_KAFKA_BOOTSTRAP_SERVERS}

query:
  service:
    grpc:
      address: ${BOOKING_SYSTEM_QUERY_SERVICE_ADDRESS}