spring:
  application:
    name: query

cassandra:
  contactPoints: ${BOOKING_SYSTEM_CASSANDRA_CONTACT_POINTS}
  keyspaceName: ${BOOKING_SYSTEM_CASSANDRA_KEYSPACE_NAME}
  localDatacenter: ${BOOKING_SYSTEM_DATACENTER}