spring:
  application:
    name: query
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      address: 0.0.0.0:${BOOKING_SYSTEM_QUERY_SERVICE_PORT:50051}

cassandra:
  contactPoints: ${BOOKING_SYSTEM_CASSANDRA_CONTACT_POINTS}
  keyspaceName: ${BOOKING_SYSTEM_CASSANDRA_KEYSPACE_NAME}
  localDatacenter: ${BOOKING_SYSTEM_DATACENTER}